/** @jsxRuntime automatic */
/** @jsxImportSource react */
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { Document, Font, Page, Path, Rect, G, Svg, StyleSheet, Text, View, renderToBuffer } from '@react-pdf/renderer';
import type { StatementView } from './view';

const C = { tinta: '#0E1020', papel: '#F4EFE6', ambar: '#F2A541', texto2: '#55536A', linea: '#E6E0D4', blanco: '#FFFFFF' };

function fontsDir(): string {
  const candidates = [
    process.env.PLUMA_PDF_FONTS_DIR,
    resolve(/*turbopackIgnore: true*/ process.cwd(), 'packages/pdf/fonts'),
    resolve(/*turbopackIgnore: true*/ process.cwd(), '../../packages/pdf/fonts'),
    resolve(/*turbopackIgnore: true*/ process.cwd(), '../pdf/fonts'),
    resolve(/*turbopackIgnore: true*/ process.cwd(), 'fonts'),
  ].filter((x): x is string => !!x);
  const found = candidates.find((d) => existsSync(resolve(/*turbopackIgnore: true*/ d, 'dm-sans-latin-400-normal.woff')));
  if (!found) throw new Error('No se encontraron las fuentes del PDF (PLUMA_PDF_FONTS_DIR)');
  return found;
}

let registered = false;
function registerFonts() {
  if (registered) return;
  const dir = fontsDir();
  Font.register({
    family: 'DM Sans',
    fonts: [
      { src: resolve(/*turbopackIgnore: true*/ dir, 'dm-sans-latin-400-normal.woff'), fontWeight: 400 },
      { src: resolve(/*turbopackIgnore: true*/ dir, 'dm-sans-latin-500-normal.woff'), fontWeight: 500 },
      { src: resolve(/*turbopackIgnore: true*/ dir, 'dm-sans-latin-700-normal.woff'), fontWeight: 700 },
    ],
  });
  Font.register({ family: 'Bricolage Grotesque', src: resolve(/*turbopackIgnore: true*/ dir, 'bricolage-grotesque-latin-800-normal.woff'), fontWeight: 800 });
  Font.registerHyphenationCallback((w) => [w]);
  registered = true;
}

const L = {
  es: { title: 'Statement oficial', period: 'Período', payDate: 'Fecha de pago', published: 'Publicado', writer: 'Autor', plan: 'Plan', summary: 'Resumen', opening: 'Saldo anterior', gross: 'Regalías brutas de tu parte', commission: 'Comisión de administración', withholding: 'Retenciones fiscales', held: 'Retenido por disputa (no se suma)', adjustments: 'Ajustes incluidos', net: 'Neto del período', closing: 'Saldo después de este statement', byWork: 'Por obra', work: 'Obra', share: 'Tu parte', grossShort: 'Bruto', netShort: 'Neto', byType: 'Por tipo de ingreso', bySource: 'Por fuente', byTerritory: 'Por territorio', footer: 'Documento oficial generado por Pluma. Conservas el 100 % de la propiedad de tus obras.', types: { performance: 'Ejecución pública', mechanical: 'Mecánicos', youtube_ugc: 'YouTube / UGC', sync: 'Sync', other: 'Otros' }, holdNote: 'en disputa' },
  en: { title: 'Official statement', period: 'Period', payDate: 'Payment date', published: 'Published', writer: 'Writer', plan: 'Plan', summary: 'Summary', opening: 'Previous balance', gross: 'Gross royalties (your share)', commission: 'Administration fee', withholding: 'Tax withholding', held: 'Held in dispute (not added)', adjustments: 'Adjustments included', net: 'Net for the period', closing: 'Balance after this statement', byWork: 'By song', work: 'Song', share: 'Your share', grossShort: 'Gross', netShort: 'Net', byType: 'By income type', bySource: 'By source', byTerritory: 'By territory', footer: 'Official document generated by Pluma. You keep 100% ownership of your songs.', types: { performance: 'Public performance', mechanical: 'Mechanicals', youtube_ugc: 'YouTube / UGC', sync: 'Sync', other: 'Other' }, holdNote: 'in dispute' },
  'pt-BR': { title: 'Statement oficial', period: 'Período', payDate: 'Data de pagamento', published: 'Publicado', writer: 'Autor', plan: 'Plano', summary: 'Resumo', opening: 'Saldo anterior', gross: 'Royalties brutos da sua parte', commission: 'Comissão de administração', withholding: 'Retenções fiscais', held: 'Retido por disputa (não somado)', adjustments: 'Ajustes incluídos', net: 'Líquido do período', closing: 'Saldo depois deste statement', byWork: 'Por obra', work: 'Obra', share: 'Sua parte', grossShort: 'Bruto', netShort: 'Líquido', byType: 'Por tipo de receita', bySource: 'Por fonte', byTerritory: 'Por território', footer: 'Documento oficial gerado pela Pluma. Você mantém 100% da propriedade das suas obras.', types: { performance: 'Execução pública', mechanical: 'Mecânicos', youtube_ugc: 'YouTube / UGC', sync: 'Sync', other: 'Outros' }, holdNote: 'em disputa' },
};

const s = StyleSheet.create({
  page: { fontFamily: 'DM Sans', fontSize: 9.5, color: C.tinta, backgroundColor: C.blanco, paddingBottom: 48 },
  band: { backgroundColor: C.tinta, paddingHorizontal: 36, paddingVertical: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  word: { fontFamily: 'Bricolage Grotesque', fontWeight: 800, fontSize: 24, color: C.papel, letterSpacing: -1 },
  bandTitle: { color: C.ambar, fontSize: 11, fontWeight: 700 },
  body: { paddingHorizontal: 36, paddingTop: 22, gap: 16 },
  meta: { flexDirection: 'row', flexWrap: 'wrap', gap: 18 },
  metaItem: { gap: 2 },
  label: { fontSize: 8, color: C.texto2, textTransform: 'uppercase', letterSpacing: 0.8 },
  value: { fontSize: 10.5, fontWeight: 700 },
  netBox: { backgroundColor: C.ambar, borderRadius: 12, padding: 16, gap: 4 },
  netAmount: { fontSize: 28, fontWeight: 700 },
  h2: { fontFamily: 'Bricolage Grotesque', fontWeight: 800, fontSize: 13, marginBottom: 6 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5, borderBottomWidth: 0.6, borderBottomColor: C.linea },
  cellMain: { flex: 1, paddingRight: 8 },
  num: { width: 90, textAlign: 'right' },
  bold: { fontWeight: 700 },
  footer: { position: 'absolute', bottom: 20, left: 36, right: 36, fontSize: 7.5, color: C.texto2, flexDirection: 'row', justifyContent: 'space-between' },
});

const BARBS = [18, 30, 44, 58, 70, 80, 86, 84, 76, 62, 44, 24];

function Symbol() {
  return (
    <Svg width={30} height={30} viewBox="0 0 220 220">
      <G transform="rotate(-42 110 110)">
        <Path d="M8 110 L22 104 L196 108 L196 112 L22 116 Z" fill={C.papel} />
        {BARBS.map((h, i) => <Rect key={i} x={43 + i * 12} y={110 - h / 2} width={7} height={h} rx={3.5} fill={C.ambar} />)}
      </G>
    </Svg>
  );
}

function StatementDoc({ v }: { v: StatementView }) {
  const t = L[v.locale];
  const money = (cents: number) => `${v.currency} ${new Intl.NumberFormat(v.intlLocale, { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(cents / 100)}`;
  const pct = (bps: number) => new Intl.NumberFormat(v.intlLocale, { style: 'percent', maximumFractionDigits: 2 }).format(bps / 10000);
  const date = (d: string) => new Intl.DateTimeFormat(v.intlLocale, { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(d));
  const Table = ({ title, rows }: { title: string; rows: { key: string; netCents: number }[] }) => (
    <View wrap={false}>
      <Text style={s.h2}>{title}</Text>
      {rows.map((r) => (
        <View key={r.key} style={s.row}>
          <Text style={s.cellMain}>{r.key}</Text>
          <Text style={s.num}>{money(r.netCents)}</Text>
        </View>
      ))}
    </View>
  );
  const summary: [string, number, boolean?][] = [
    [t.opening, v.totals.openingCents],
    [t.gross, v.totals.grossCents],
    [`${t.commission} (${pct(v.plan.commissionBps)})`, 0 - v.totals.commissionCents || 0],
    [t.withholding, 0 - v.totals.withholdingCents || 0],
    [t.net, v.totals.netCents, true],
    [t.closing, v.totals.closingCents, true],
  ];
  return (
    <Document title={`Pluma · ${t.title} · ${v.periodCode}`} author="Pluma" creator="Pluma" producer="Pluma">
      <Page size="A4" style={s.page}>
        <View style={s.band}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            <Symbol />
            <Text style={s.word}>pluma</Text>
          </View>
          <Text style={s.bandTitle}>{t.title} · {v.periodCode}</Text>
        </View>
        <View style={s.body}>
          <View style={s.meta}>
            <View style={s.metaItem}><Text style={s.label}>{t.writer}</Text><Text style={s.value}>{v.writer.artistName ? `${v.writer.artistName} · ${v.writer.legalName}` : v.writer.legalName}</Text></View>
            <View style={s.metaItem}><Text style={s.label}>{t.period}</Text><Text style={s.value}>{v.periodCode}</Text></View>
            <View style={s.metaItem}><Text style={s.label}>{t.payDate}</Text><Text style={s.value}>{date(v.payDate)}</Text></View>
            <View style={s.metaItem}><Text style={s.label}>{t.plan}</Text><Text style={s.value}>{v.plan.code === 'pro' ? 'Pro' : v.locale === 'pt-BR' ? 'Sócio' : 'Socio'} · {pct(v.plan.commissionBps)}</Text></View>
            {v.writer.ipi && <View style={s.metaItem}><Text style={s.label}>IPI</Text><Text style={s.value}>{v.writer.ipi}</Text></View>}
          </View>
          <View style={s.netBox}>
            <Text style={{ fontSize: 9, fontWeight: 500 }}>{t.net}</Text>
            <Text style={s.netAmount}>{money(v.totals.netCents)}</Text>
          </View>
          <View wrap={false}>
            <Text style={s.h2}>{t.summary}</Text>
            {summary.map(([k, val, strong]) => (
              <View key={k} style={s.row}>
                <Text style={[s.cellMain, strong ? s.bold : {}]}>{k}</Text>
                <Text style={[s.num, strong ? s.bold : {}]}>{money(val)}</Text>
              </View>
            ))}
            {v.totals.adjustmentsCents !== 0 && <View style={s.row}><Text style={s.cellMain}>{t.adjustments}</Text><Text style={s.num}>{money(v.totals.adjustmentsCents)}</Text></View>}
            {v.totals.heldCents !== 0 && <View style={s.row}><Text style={s.cellMain}>{t.held}</Text><Text style={s.num}>{money(v.totals.heldCents)}</Text></View>}
          </View>
          <View>
            <Text style={s.h2}>{t.byWork}</Text>
            <View style={[s.row, { borderBottomColor: C.tinta }]}>
              <Text style={[s.cellMain, s.label]}>{t.work}</Text><Text style={[s.num, s.label]}>{t.share}</Text><Text style={[s.num, s.label]}>{t.grossShort}</Text><Text style={[s.num, s.label]}>{t.netShort}</Text>
            </View>
            {v.byWork.map((w) => (
              <View key={w.title} style={s.row} wrap={false}>
                <Text style={s.cellMain}>{w.title}{w.held ? ` (${t.holdNote})` : ''}</Text>
                <Text style={s.num}>{pct(w.shareBps)}</Text>
                <Text style={s.num}>{money(w.grossCents)}</Text>
                <Text style={[s.num, s.bold]}>{money(w.netCents)}</Text>
              </View>
            ))}
          </View>
          <Table title={t.byType} rows={v.byIncomeType.map((r) => ({ key: (t.types as Record<string, string>)[r.key] ?? r.key, netCents: r.netCents }))} />
          <Table title={t.bySource} rows={v.bySource} />
          <Table title={t.byTerritory} rows={v.byTerritory} />
        </View>
        <View style={s.footer} fixed>
          <Text>{t.footer}</Text>
          <Text render={({ pageNumber, totalPages }) => `${v.statementId.slice(0, 8)} · ${pageNumber}/${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}

export async function renderStatementPdf(view: StatementView): Promise<Buffer> {
  registerFonts();
  return renderToBuffer(<StatementDoc v={view} />);
}
